### ISSUE TITLE
Log not created

### ISSUE THREAD

**Issue by udovicic** [MonriPayments/magento2-plugin#20]
## Preconditions:
Software versions:
- monripayments/magento2: 1.2.0
- magento/product-community-edition: 2.4.5-p1
- PHP version: 8.1.11

Magento & Monri configured in sandbox mode
Monri is configured only for "Monri components", nothing from "Monri Redirect" changed.
Enabled "Debug" under "Monri components"

## Steps to reproduce:
1. Add product to the cart
2. Complete checkout

## Expected result:
Magento log "monri_payments.log" was created with transaction details for debugging purposes

## Actual results:
The log is not created

## Additional notes:
The log is created once the "Debug" config is changed under "Monri Redirect", meaning that the config is being fetched from the wrong path.

**Comment by ivanweiler** [comment]
Resolved in v.1.3.0, closing issue
