### ISSUE TITLE
Checkout issues with HR symbols

### ISSUE THREAD

**Issue by udovicic** [MonriPayments/magento2-plugin#22]
This piece of code [here](https://github.com/MonriPayments/magento2-plugin/blob/master/Gateway/Request/Redirect/CustomerInfoBuilder.php#L78-L86) has a problem with HR symbols.

For example, if I input my first name as `Stjepan` and my last name as `Udovičić xxxxxxxxxxć`, then `formatText()` will return the invalid value. Ultimately, the order will be created, but the redirect will fail, as data can not be serialized for sending. following is observed in the log file:

```
[2023-02-03T14:17:13.163515+01:00] main.DEBUG: array (
  'location' => 'Monri\\Payments\\Controller\\Redirect\\Form\\Data::execute',
  'errors' => 
  array (
    0 => 'Unexpected exception caught: Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded',
  ),
  'success' => false,
  'payload' => 
  array (
  ),
) [] []
``` 

The result is that the customer is left on checkout with an empty error message, can't retry as the order is created, and has to re-add everything back to the cart.

![image](https://user-images.githubusercontent.com/1079201/216617327-164bb4f6-7e58-4fef-8898-10aef85c0d36.png)

**Relevant data:**
**Module version**: _1.2.0_
**Magento version**: _magento/project-community-edition: 2.4.4-p2_
**PHP version**: _7.4.11_

**Comment by bbutkovic** [comment]
Thank you for reporting the issue, we'll investigate this and report back.

**Comment by udovicic** [comment]
Hi, do you have any updates on this one?

**Comment by ivanweiler** [comment]
Hi @udovicic Fix is prepared and tested for the next release. 

It is not prioritized as "urgent bugfix" since in practice case would rarely happen (customer would need to have first+lastname over 30 characters).

Changes:
https://github.com/MonriPayments/magento2-plugin/commit/02cf8bb282299a68d361b4fc3b4229ebb881167f

If needed, we can provide Magento patch before official release, let us know.

**Comment by udovicic** [comment]
Thanks for the link and details!
